// Generated by CoffeeScript 1.4.0
var Person, get, person, set;

get = Em.get;

set = Em.set;

Person = window.Person;

person = window.person;

describe('Compr:', function() {
  beforeEach(function() {
    Person = Em.Object.extend(ValidateMixin, {
      validations: {
        age: [
          {
            compr: '@<10'
          }
        ]
      }
    });
    return person = Person.create();
  });
  afterEach(function() {
    return person = null;
  });
  it('age is out of range', function() {
    set(person, 'age', 20);
    person.validate();
    assert.equal(get(person, '_errors.age'), '¬ !comparison: 20<10');
    return assert.equal(get(person, '_isValid'), false);
  });
  return it('age is ok', function() {
    set(person, 'age', 5);
    person.validate();
    assert.equal(get(person, '_errors.age'), void 0);
    return assert.equal(get(person, '_isValid'), true);
  });
});
