// Generated by CoffeeScript 1.4.0
var Person, get, person, set;

get = Em.get;

set = Em.set;

Person = window.Person;

person = window.person;

describe('email:', function() {
  beforeEach(function() {
    Person = Em.Object.extend(ValidateMixin, {
      validations: {
        email: ['presence', 'email']
      }
    });
    return person = Person.create({
      email: 'g'
    });
  });
  afterEach(function() {
    return person = null;
  });
  it('email is absent', function() {
    person.validate();
    assert.equal(get(person, '_errors.email'), '¬ wrong email format');
    return assert.equal(get(person, '_isValid'), false);
  });
  it('email format is wrong', function() {
    set(person, 'email', 'jc.c');
    person.validate();
    assert.equal(get(person, '_errors.email'), '¬ wrong email format');
    return assert.equal(get(person, '_isValid'), false);
  });
  return it('email is ok', function() {
    set(person, 'email', 'j@c.c');
    person.validate();
    assert.equal(get(person, '_errors.email'), void 0);
    return assert.equal(get(person, '_isValid'), true);
  });
});
