// Generated by CoffeeScript 1.4.0
var Person, get, person, set;

get = Em.get;

set = Em.set;

Person = window.Person;

person = window.person;

describe("regex:", function() {
  beforeEach(function() {
    Person = Em.Object.extend(ValidateMixin, {
      validations: {
        tel: [/^(?:0|\+?254)7\d{8}$/]
      }
    });
    return person = Person.create({
      tel: ""
    });
  });
  afterEach(function() {
    return person = null;
  });
  it("fail", function() {
    person.set("tel", "254000111222");
    person.validate();
    return assert.equal(get(person, "_isValid"), false);
  });
  return it("pass", function() {
    person.set("tel", "254700111222");
    person.validate();
    assert.equal(get(person, "_errors.tel"), void 0);
    return assert.equal(get(person, "_isValid"), true);
  });
});
