// Generated by CoffeeScript 1.6.1
var Person, get, person, set;

get = Em.get;

set = Em.set;

Person = window.Person;

person = window.person;

describe('Length:', function() {
  beforeEach(function() {
    Person = Em.Object.extend(ValidateMixin, {
      validations: {
        books: [
          {
            length: '@<10'
          }
        ]
      }
    });
    return person = Person.create();
  });
  afterEach(function() {
    return person = null;
  });
  it('books length is out of range', function() {
    set(person, 'books', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18]);
    person.validate();
    assert.equal(get(person, '_errors.books'), '¬ !length: 19<10');
    return assert.equal(get(person, '_isValid'), false);
  });
  return it('books length is ok', function() {
    set(person, 'books', [0, 1, 2, 3, 4, 5]);
    person.validate();
    assert.equal(get(person, '_errors.books'), void 0);
    return assert.equal(get(person, '_isValid'), true);
  });
});
