// Generated by CoffeeScript 1.6.1
var Person, get, person, set;

get = Em.get;

set = Em.set;

Person = window.Person;

person = window.person;

describe("presence:", function() {
  beforeEach(function() {
    Person = Em.Object.extend(ValidateMixin, {
      validations: {
        name: ["presence"]
      }
    });
    return person = Person.create({
      name: ""
    });
  });
  afterEach(function() {
    return person = null;
  });
  it("name is absent", function() {
    person.validate();
    assert.equal(get(person, "_errors.name"), "");
    assert.equal(get(person, "_isValid"), false);
    set(person, "name", "  ");
    person.validate();
    assert.equal(get(person, "_errors.name"), "");
    return assert.equal(get(person, "_isValid"), false);
  });
  return it("name is present", function() {
    set(person, "name", "Yehuda");
    person.validate();
    assert.equal(get(person, "_errors.name"), void 0);
    return assert.equal(get(person, "_isValid"), true);
  });
});
