// Generated by CoffeeScript 1.4.0
var Em, get, set;

Em = window.Em;

get = Em.get;

set = Em.set;

module.exports = Em.Object.extend({
  msg: "Long",
  validate: function() {
    var attr, equal, max, obj, val;
    obj = get(this, "obj");
    attr = get(this, "attr");
    max = get(this, "max");
    equal = get(this, "equal");
    val = get(obj, attr);
    if (equal && (val.length <= max) === false) {
      return false;
    } else if (val.length > max) {
      return false;
    }
  }
});
