// Generated by CoffeeScript 1.4.0
var Em, get, set;

Em = window.Em;

get = Em.get;

set = Em.set;

module.exports = Em.Object.extend({
  msg: "invalid",
  validate: function() {
    var attr, negative, obj, positive, val, zero;
    obj = get(this, "obj");
    attr = get(this, "attr");
    zero = get(this, "zero");
    positive = get(this, "positive");
    negative = get(this, "negative");
    val = parseInt(get(obj, attr));
    if (isNaN(val)) {
      return false;
    } else if (zero && val === 0) {
      return true;
    } else if (val === 0) {
      return false;
    } else if (positive && val < 0) {
      return false;
    } else if (negative && val > 0) {
      return false;
    }
  }
});
