// Generated by CoffeeScript 1.4.0
var Em, get, set;

Em = window.Em;

get = Em.get;

set = Em.set;

module.exports = Em.Object.extend({
  msg: (function() {
    var attr, obj, re, val;
    obj = get(this, "obj");
    attr = get(this, "attr");
    re = get(this, "re");
    val = get(obj, attr);
    return "" + val + " doesn't match " + re;
  }).property("re"),
  validate: function() {
    var attr, obj, re, val;
    obj = get(this, "obj");
    attr = get(this, "attr");
    re = get(this, "re");
    val = get(obj, attr);
    if (!(val.match(re))) {
      return false;
    }
  }
});
