// Generated by CoffeeScript 1.4.0
var Em, get, set;

Em = window.Em;

get = Em.get;

set = Em.set;

Em.TextSupport.reopen({
  isValid: true,
  error: void 0,
  classNameBindings: ['isValid::error'],
  init: function() {
    var context, that, _for;
    this._super();
    that = this;
    _for = get(this, 'for');
    context = get(this, 'context');
    return context.reopen({
      validate: function() {
        var error, isValid;
        this._super();
        error = get(this, "_errors." + _for);
        isValid = error === void 0;
        return that.setProperties({
          error: error,
          isValid: isValid
        });
      }
    });
  }
});
